### ISSUE TITLE
Question about the dense caption evaluation

### ISSUE THREAD

**Issue by ch3cook-fdu** [3d-vista/3D-VisTA#13]
It seems like the evaluation codes in https://github.com/3d-vista/3D-VisTA/blob/main/pipeline/pipeline_mixin.py#L291-L345 score the captions regardless of box IoUs, thus the output results could not match the reported values.

**Comment by zhuziyu-edward** [comment]
Hi, we have three settings, gt scores regardless of IoU, scores of IoU25, and scores of IoU50. You should set pc_type to pred and  set iou_threshold to 25 or 50 to get results. The default setting is captions regardless of IoU.
