### ISSUE TITLE
How do I run the pre-training script?

### ISSUE THREAD

**Issue by LZ-CH** [3d-vista/3D-VisTA#14]
Dear author:

Thanks for your interesting work.

I have downloaded the pre-training data from Hugging face. How do I run the pre-training script? Or when will pre-training related script be released?

Thanks!!

**Comment by XiangyangLi20** [comment]
Dear authors:

Thanks for your interesting work.

Can you share us with the data/scanfamily/annotations/ data？

**Comment by LZ-CH** [comment]
Dear author: 

Could you please also share the complete pretraining dataset(From ScanNet and 3RScan)  used in your paper if possible?  Because I don’t know the specific script you used to process the ScanQA data. This will greatly facilitate our process of replicating pre-training.

Thanks!!

**Comment by zhuziyu-edward** [comment]
Thank you for your interests in our work. You can follow 3R-Scan repo to process scenes. Since copyright protection, we cannot upload them right now. ScanQA data processing is already implemented in our dataset, you can use it as well.
