### ISSUE TITLE
Request for the data/scanfamily/annotations data

### ISSUE THREAD

**Issue by lixyresearch** [3d-vista/3D-VisTA#16]
Dear Authors,

Thank you for your intriguing work.

Would it be possible to make the "data/scanfamily/annotations" data publicly accessible?

**Comment by lixyresearch** [comment]
Sorry for the disturbance, we have found it.

**Comment by lx709** [comment]
Hello @xiangyangli-cn , same question, where you found the scanfamily data?

**Comment by cy94** [comment]
Hi @xiangyangli-cn could you mention where you found these files?
