### ISSUE TITLE
save_mask.zip for ScanRefer training

### ISSUE THREAD

**Issue by ZoomPkk** [3d-vista/3D-VisTA#17]
Hello,thanks for your great work！
I notice that in save_mask.zip,there are only detection results for evaluating,could you release the save_mask.zip of the other scenes for ScanRefer training?
I would really appreciate it,thank you!

**Comment by zhuziyu-edward** [comment]
Sure, you can find it in this issue #12, here is the link https://drive.google.com/file/d/1w9m3lCW67Tul8qbkES7paX0cFXjblQ-C/view?usp=share_link.

**Comment by ZoomPkk** [comment]
Got it.Thanks for your reply!
