### ISSUE TITLE
scanrefer_vocab.pth and other files missing

### ISSUE THREAD

**Issue by deeptibhegde** [3d-vista/3D-VisTA#22]
Hello, 
 When I try to run scan2cap, I get the following error:

FileNotFoundError: [Errno 2] No such file or directory: './data/scanfamily/annotations/meta_data/scanrefer_vocab.pth'

where can I find this file?

The files of sr3d and nr3d also seem to be different than those linked. Can you point me in the direction of the '.jsonl' files under annotations/refer ?

**Comment by deeptibhegde** [comment]
I was able to perform the inference on nr3d by directly converting the csv files to jsonl, however, the token length of the samples in sr3d seem to be much longer than 25, which is the threshold in the dataloader. Am I using the correct annotations for the sr3d task? I obtained it from the official referit3d dataset.

**Comment by X-coder-beam** [comment]
1. You can use utils/build_vocabulary to generate vocab.pth file. 
2. Sr3D may contain texts longer than 25. This threshold is referit3d repo.

**Comment by yesoly** [comment]
Hello,
I successfully created the file 'scanrefer_vocab.pth' thanks to your guidance.

However, I'm encountering difficulty generating 'scanrefer_corpus.pth'.
Could you please advise on where I can find this file or how to create it?
Your assistance would be greatly appreciated.

Thank you!
