### ISSUE TITLE
Question about tgt_object_id

### ISSUE THREAD

**Issue by WeitaiKang** [3d-vista/3D-VisTA#23]
Hi, authors, thanks for your attempt on 3D pretraining job.

I have a question about the tgt_object_id of ScanReferDataset. In #12, you implied that the point clouds are sorted by score. If I understand correctly, it's in a descending order of the scores, as you extract [the former 50 objects](https://github.com/3d-vista/3D-VisTA/blob/3f0575df6aa69d151849d9e643581b3dc31cef51/dataset/dataset_mixin.py#L76). Then I am confused that why the tgt_object_id is set to [the lowest / last score's idx](https://github.com/3d-vista/3D-VisTA/blob/3f0575df6aa69d151849d9e643581b3dc31cef51/dataset/scanrefer.py#L141) to supervise the [cross_entropy](https://github.com/3d-vista/3D-VisTA/blob/3f0575df6aa69d151849d9e643581b3dc31cef51/optimization/loss_function.py#L10)?

**Comment by zhuziyu-edward** [comment]
Because during training, tgt_object is the first object in the object list, see dataset selected_ids part.
