### ISSUE TITLE
Ask for more Mask3D results

### ISSUE THREAD

**Issue by WeitaiKang** [3d-vista/3D-VisTA#24]
Hi authors, thanks for your project.

I am now finetuning your model on my private dataset, which is a kind of 3D visual grounding.

However, i found that the segmentation results from the Mask3D in your project only include the scenes of ScanRefer.

I wonder if you have more Mask3D results that contains all the scenes of ScanNet.

Looking forward to your response!

**Comment by zhuziyu-edward** [comment]
We only save mask3d results for scanrefer evaluation. You can run Mask3D code and save these mask to npz format

**Comment by WeitaiKang** [comment]
Okay thanks!
