### ISSUE TITLE
`scannetv2_raw_categories.json` and `cat2glove42b.json` missing?

### ISSUE THREAD

**Issue by cy94** [3d-vista/3D-VisTA#25]
Hi, when trying to finetune on ScanQA it looks for  `scannetv2_raw_categories.json` and `cat2glove42b.json` which I couldn't find. Could you please add these files?

**Comment by zhuziyu-edward** [comment]
These files are Scannet configuration files, which is provided in our Readme. The link is here [https://github.com/cshizhe/vil3dref](url)
