### ISSUE TITLE
Question Regarding Evaluation Metrics in ScanQA

### ISSUE THREAD

**Issue by vpeiyun97** [3d-vista/3D-VisTA#27]
Hello, I have questions about the evaluation metric settings in ScanQA.

1. In the code, I see that metrics like CIDEr and BLEU are only configured within the def eval_caption() function, whereas in def eval_qa(), only the EM@1 and EM@10 metrics are calculated. However, in the paper, BLEU and similar metrics are also reported in the scanQA results. Could you advise on how I can calculate these metrics for the QA section?

2. Additionally, to test the results for "test w/ object" and "test w/o object," is it correct to change the split parameter in pipeline.py from val to the corresponding value?

Looking forward to your response. Thank you!

**Comment by haaaappy** [comment]
I'd like to know the outputs now is "test w/ object" or "test w/o object"?
