### ISSUE TITLE
pointnet2 installing error

### ISSUE THREAD

**Issue by jiafei1224** [3d-vista/3D-VisTA#3]
Hi,
Can you provide more details on installing the pointnet2? I have issue install pointnet2==3.0.0.

Thank you

**Comment by zhuziyu-edward** [comment]
What is the python, pytorch, and cuda version? You should install pytorch, cuda first, then install pointnet2.

**Comment by liqing-ustc** [comment]
@jiafei1224 You probably need to install pointnet2 from its source code:
```
cd vision/pointnet2
python3 setup.py install
```
