### ISSUE TITLE
code and dataset

### ISSUE THREAD

**Issue by nanfengguli** [3d-vista/3D-VisTA#4]
Thanks for your work, so when will it be fully open source?

**Comment by nanfengguli** [comment]
I'm still new to visual grounding work, and I'd like to ask if your current solution can be functional in new scanned scenes (I mean, realistic scenes scanned by myself)?

**Comment by nanfengguli** [comment]
Apart from that, can you provide some guidance on the piece of making datasets using LLMs? Like a more detailed process of making them.

**Comment by zhuziyu-edward** [comment]
We just release codes for all downstream tasks, you can check our new update. If you have instance segmentation masks of new scenes, I think our model can work.
