### ISSUE TITLE
Can not find scanrefer_corpus.pth & scanrefer_vocab.pth?

### ISSUE THREAD

**Issue by Xiaolong-RRL** [3d-vista/3D-VisTA#6]
Dear author:

Thanks for your interesting work.

According to the instructions in the readme, I didn't find these two files: scanrefer_corpus.pth & scanrefer_vocab.pth, could you tell me how to find them correctly?

Thanks!!

**Comment by Xiaolong-RRL** [comment]
Another question: 

I noticed that the checkpoints' names seem to be wrong, are they correct?

**Comment by zhuziyu-edward** [comment]
Hi, we have updated checkpoints path in readme you can check again.

**Comment by zhuziyu-edward** [comment]
You can build scanrefer_corpus.pth from dataest/scan2cap.py and scanrefer_vocab.pth from utils/build_vocabulary.py

**Comment by Xiaolong-RRL** [comment]
I see, thanks!!
