### ISSUE TITLE
The `ScanScribe` dataset

### ISSUE THREAD

**Issue by ch3cook-fdu** [3d-vista/3D-VisTA#7]
I have noticed a released version at https://huggingface.co/datasets/edward2021/ScanScribe/tree/main, but the scene_ids seem strange and not correspond to a similar form as `scene0000_00`.

**Comment by zhuziyu-edward** [comment]
Yes, these are ids from 3R-Scan dataset.

**Comment by ch3cook-fdu** [comment]
Thanks for the reply! Will the pre-training scripts and pre-training dataset on ScanNet be released?

**Comment by zhuziyu-edward** [comment]
For the ScanNet part, training data are formed from existing dataset including ScanRefer, ScanQA, and Referit3D.
