### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by HaibiaoXuan** [3d-vista/3D-VisTA#8]
Is the demo code currently available? That is, use my own description to get the appropriate grounding results.

**Comment by zhuziyu-edward** [comment]
Hi, current code can only inference on ScanNet scenes. If you want to use your own description, you can add them to a new .json file and load them in scanrefer dataset. Then run evaludation and get result. We export result to render engine like Open3D and blender to create demo.

**Comment by HaibiaoXuan** [comment]
If having object detection boxes for my own scene, can I use VisTA to achieve Grounding, QA, etc.?
The description may only involve relationships, e.g. "cabinet next to the bed"

**Comment by zhuziyu-edward** [comment]
If object shape is similiar to scannet, I think 3D-VisTA can work.
